---
  kind: pipeline
  type: docker
  name: default
  
  steps:
  - name: validate
    image: hashicorp/terraform:light
    commands:
    - terraform init
    - terraform validate
  
  - name: build
    image: hashicorp/terraform:light
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
    commands:
    - terraform init
    - terraform plan -out plano.out

